export const keys = [
// <type>,  <mutable>, <keyCode>,
// <name(en)>, <input(en)>, <input(en) + shift>,
// <name(ru)>, <input(ru)>, <input(ru) + shift>
  ['char', true, 'Backquote', '~`', '`', '~', 'Ё', 'ё', 'Ё'],
  ['char', false, 'Digit1', '!1', '1', '!', '!1', '1', '!'],
  ['char', false, 'Digit2', '@2', '2', '@', '"2', '2', '"'],
  ['char', false, 'Digit3', '#3', '3', '#', '№3', '3', '№'],
  ['char', false, 'Digit4', '$4', '4', '$', ';4', '4', ';'],
  ['char', false, 'Digit5', '%5', '5', '%', '%5', '5', '%'],
  ['char', false, 'Digit6', '^6', '6', '^', ':6', '6', ':'],
  ['char', false, 'Digit7', '&7', '7', '&', '?7', '7', '?'],
  ['char', false, 'Digit8', '*8', '8', '*', '*8', '8', '*'],
  ['char', false, 'Digit9', '(9', '9', '(', '(9', '9', '('],
  ['char', false, 'Digit0', ')0', '0', ')', ')0', '0', ')'],
  ['char', false, 'Minus', '_-', '-', '_'],
  ['action', false, 'Backspace', 'Backspace'],
  ['char', true, 'KeyQ', 'Q', 'q', 'Q', 'Й', 'й', 'Й'],
  ['char', true, 'KeyW', 'W', 'w', 'W', 'Ц', 'ц', 'Ц'],
  ['char', true, 'KeyE', 'E', 'e', 'E', 'У', 'у', 'У'],
  ['char', true, 'KeyR', 'R', 'r', 'R', 'К', 'к', 'К'],
  ['char', true, 'KeyT', 'T', 't', 'T', 'Е', 'е', 'Е'],
  ['char', true, 'KeyY', 'Y', 'y', 'Y', 'Н', 'н', 'Н'],
  ['char', true, 'KeyU', 'U', 'u', 'U', 'Г', 'г', 'Г'],
  ['char', true, 'KeyI', 'I', 'i', 'I', 'Ш', 'ш', 'Ш'],
  ['char', true, 'KeyO', 'O', 'o', 'O', 'Щ', 'щ', 'Щ'],
  ['char', true, 'KeyP', 'P', 'p', 'P', 'З', 'з', 'З'],
  ['char', true, 'BracketLeft', '{[', '[', '{', 'Х', 'х', 'Х'],
  ['char', true, 'BracketRight', '}]', ']', '}', 'Ъ', 'ъ', 'Ъ'],
  ['action', false, 'Delete', 'DEL'],
  ['char', true, 'KeyA', 'A', 'a', 'A', 'Ф', 'ф', 'Ф'],
  ['char', true, 'KeyS', 'S', 's', 'S', 'Ы', 'ы', 'Ы'],
  ['char', true, 'KeyD', 'D', 'd', 'D', 'В', 'в', 'В'],
  ['char', true, 'KeyF', 'F', 'f', 'F', 'А', 'а', 'А'],
  ['char', true, 'KeyG', 'G', 'g', 'G', 'П', 'п', 'П'],
  ['char', true, 'KeyH', 'H', 'h', 'H', 'Р', 'р', 'Р'],
  ['char', true, 'KeyJ', 'J', 'j', 'J', 'О', 'о', 'О'],
  ['char', true, 'KeyK', 'K', 'k', 'K', 'Л', 'л', 'Л'],
  ['char', true, 'KeyL', 'L', 'l', 'L', 'Д', 'д', 'Д'],
  ['char', true, 'Semicolon', ':;', ';', ':', 'Ж', 'ж', 'Ж'],
  ['char', true, 'Quote', '"\'', '\'', '"', 'Э', 'э', 'Э'],
  ['action', false, 'Enter', 'ENTER'],
  ['action', false, 'CapsLock', 'Caps Lock'],
  ['char', true, 'KeyZ', 'Z', 'z', 'Z', 'Я', 'я', 'Я'],
  ['char', true, 'KeyX', 'X', 'x', 'X', 'Ч', 'ч', 'Ч'],
  ['char', true, 'KeyC', 'C', 'c', 'C', 'С', 'с', 'C'],
  ['char', true, 'KeyV', 'V', 'v', 'V', 'М', 'м', 'М'],
  ['char', true, 'KeyB', 'B', 'b', 'B', 'И', 'и', 'И'],
  ['char', true, 'KeyN', 'N', 'n', 'N', 'Т', 'т', 'Т'],
  ['char', true, 'KeyM', 'M', 'm', 'M', 'Ь', 'ь', 'Ь'],
  ['char', true, 'Comma', '<,', ',', '<', 'Б', 'б', 'Б'],
  ['char', true, 'Period', '>.', '.', '>', 'Ю', 'ю', 'Ю'],
  ['char', true, 'Slash', '?/', '/', '?', ',.', '.', ','],
  ['action', false, 'ArrowLeft', '\u2190'],
  ['action', false, 'ArrowRight', '\u2192'],
  ['action', false, 'ShiftLeft', 'Shift'],
  ['char', false, 'Space', '', ' '],
  ['action', false, 'Lang', 'En/Ru'],
];

export const stretchKeys = ['Backspace', 'Delete', 'CapsLock', 'Enter', 'Space', 'ShiftLeft', 'Lang'];
export const firstInRow = ['KeyA', 'KeyQ', 'CapsLock', 'ShiftLeft', 'Backquote'];
